-- Snowflake analytics schema for curated TradeFlow exports.

CREATE DATABASE IF NOT EXISTS TRADEFLOW;
CREATE SCHEMA IF NOT EXISTS TRADEFLOW.CURATED;

CREATE OR REPLACE TABLE TRADEFLOW.CURATED.DAILY_TRADE_SUMMARY (
    TRADE_DATE DATE,
    SYMBOL VARCHAR,
    SIDE VARCHAR,
    CURRENCY VARCHAR,
    TRADE_COUNT NUMBER,
    TOTAL_QUANTITY NUMBER,
    GROSS_NOTIONAL NUMBER(18, 2),
    NET_SIGNED_NOTIONAL NUMBER(18, 2),
    AVG_PRICE NUMBER(18, 4),
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TRADEFLOW.CURATED.ACCOUNT_POSITION_SUMMARY (
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    REGION VARCHAR,
    STATUS VARCHAR,
    TRADE_COUNT NUMBER,
    NET_SIGNED_NOTIONAL NUMBER(18, 2),
    GROSS_NOTIONAL NUMBER(18, 2),
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TRADEFLOW.CURATED.RECONCILIATION_RESULTS (
    CHECK_NAME VARCHAR,
    SOURCE_TABLE VARCHAR,
    TARGET_TABLE VARCHAR,
    STATUS VARCHAR,
    METRIC_VALUE VARCHAR,
    DETAILS VARCHAR,
    AUDIT_TS TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Example stage load. Replace the stage URL and integration for your account.
CREATE OR REPLACE FILE FORMAT TRADEFLOW.CURATED.PARQUET_FORMAT
    TYPE = PARQUET;

-- COPY INTO TRADEFLOW.CURATED.DAILY_TRADE_SUMMARY
-- FROM @tradeflow_curated_stage/gold/daily_trade_summary/
-- FILE_FORMAT = TRADEFLOW.CURATED.PARQUET_FORMAT
-- MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
